### ISSUE TITLE
keep stable and beta releases separate

### ISSUE THREAD

**Issue by piramiday** [pia-foss/desktop#10]
the latest commit on the `master` branch, 754080ce15b6e3555321dde2dcfd0c21ec25b1a9, pushed a beta update.

wouldn't it be better to push **only stable releases** to the `master` branch, while pushing beta stuff in an aptly named `beta` branch?

**Comment by JonathonH-PIA** [comment]
@piramiday Yeah, I agree this has created some confusion.  The master branch is now 2.2.0, and I've started creating tags for releases too.  Next time we have a beta release, I'll handle this differently.  Thanks for the feedback!
