### ISSUE TITLE
LFS data quota exceeded

### ISSUE THREAD

**Issue by vezquex** [pia-foss/desktop#11]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

$ git-lfs filter-process
Error downloading object: brands/pia/gen_res/img/tray/sample-auto.png (e88793e): Smudge error: Error downloading brands/pia/gen_res/img/tray/sample-auto.png (e88793e7400fdc69ec82c9d778a34b525b0f6624a6cfd26d78897b1a404ff6cf):

**Comment by JonathonH-PIA** [comment]
Thanks @vezquex , this is resolved now, I'm able to clone the desktop repo again.
