### ISSUE TITLE
Minimize to tray on startup on Linux

### ISSUE THREAD

**Issue by rwtallant13** [pia-foss/desktop#19]
An option to minimize the client to tray on start up on Linux would be fantastic. I'm unsure if this exists already for windows/mac but as far as i can tell this is not possible on the Linux desktop client at the moment.

**Comment by silelmot** [comment]
My Client starts minimized on default.
I just looked into the autostart and there it starts with the "-q" - Parameter.

**Comment by rwtallant13** [comment]
For some reason '-q' does not work for me but '--quiet' does, which is what is in my autostart file on Arch Linux. Thanks for the idea of looking there.

Could you show me where you looked into the options for the client i have not been able to find them documented anywhere. 

Thanks again

**Comment by banister** [comment]
Closing as it appears the two of you figured this out already :)
