### ISSUE TITLE
Using ip instead of ifconfig

### ISSUE THREAD

**Issue by kevinlekiller** [pia-foss/desktop#20]
**Is your feature request related to a problem? Please describe.**
ifconfig, part of net-tools has not been updated since 2001, and is marked as deprecated/obsolete, and is not available on some distros, it's also not recommended to be used.

**Describe the solution you'd like**
Utilizing ip (iproute2) instead of ifconfig would allow better support for those distros that do not have access to ifconfig.

**Describe alternatives you've considered**
For now, of course it's possible for the user to maintain their own build of net-tools if it's not available in the distro's package management system, but it's an inconvinience when ip is available across all distros.

**Additional context**
https://www.reddit.com/r/linux4noobs/comments/bse3wm/is_ifconfig_deprecated/

https://ubuntu.com/blog/if-youre-still-using-ifconfig-youre-living-in-the-past

https://serverfault.com/questions/458628/should-i-quit-using-ifconfig

https://access.redhat.com/sites/default/files/attachments/rh_ip_command_cheatsheet_1214_jcs_print.pdf

https://linux.die.net/man/8/ifconfig

https://wiki.linuxfoundation.org/networking/net-tools

**Comment by JonathonH-PIA** [comment]
At last, this is addressed in 2.9.0!  I'll close this issue.
