### ISSUE TITLE
I got some errors on Win10

### ISSUE THREAD

**Issue by ErrorExorY** [pia-foss/desktop#21]
**Describe the bug**

**To Reproduce**
1. I have all Prerequisites installed as it said in the doumentation but i got that strange error:

`C:\Users\FL Studio\Documents\desktop>rake artifacts
Architecture not known: "OSArchitecture=64-Bit"
rake aborted!
TypeError: no implicit conversion of nil into String
C:/Users/FL Studio/Documents/desktop/rake/model/qt.rb:51:in "directory?"
C:/Users/FL Studio/Documents/desktop/rake/model/qt.rb:51:in "initialize"
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in "new"
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in "<class:Executable>"
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:41:in "<top (required)>"
C:/Users/FL Studio/Documents/desktop/Rakefile:2:in "require_relative"
C:/Users/FL Studio/Documents/desktop/Rakefile:2:in "<top (required)>"
(See full trace by running task with--trace)`

**Expected behavior**
The builded project.
**Observed on:**
 - OS: [Windows 10]

**Comment by ErrorExorY** [comment]
--trace 

C:\Users\FL Studio\Documents\desktop>rake --trace
Architecture not known: "OSArchitecture=64-Bit"
rake aborted!
TypeError: no implicit conversion of nil into String
C:/Users/FL Studio/Documents/desktop/rake/model/qt.rb:51:in `directory?'
C:/Users/FL Studio/Documents/desktop/rake/model/qt.rb:51:in `initialize'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in `new'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in `<class:Executable>'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:41:in `<top (required)>'
C:/Users/FL Studio/Documents/desktop/Rakefile:2:in `require_relative'
C:/Users/FL Studio/Documents/desktop/Rakefile:2:in `<top (required)>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
C:/Ruby27-x64/bin/rake:23:in `load'
C:/Ruby27-x64/bin/rake:23:in `<main>'

**Comment by kevinlekiller** [comment]
You didn't set the OSArchitecture properly: https://github.com/pia-foss/desktop#configurations

**Comment by JonathonH-PIA** [comment]
@ErrorExorY Looks like a bug in `hostArchitecture` in util.rb.  It's looking for `OSArchitecture=64-bit`, but your system seems to return `OSArchitecture=64-Bit` with a capital B.

Could you try tweaking the regex in `hostArchitecture` to be case-insensitive?  `if(archProbe.match?(/^OSArchitecture=64-bit$/i))` (add `i` flag)

Or, adding `ARCHITECTURE=x86_64` to the rake command line should work around it like @kevinlekiller suggested.

**Comment by ErrorExorY** [comment]
Now I changed the build.rb wit capital B but got that error left:

TypeError: no implicit conversion of nil into String
C:/Users/FL Studio/Documents/desktop/rake/model/qt.rb:51:in directory?' C:/Users/FL Studio/Documents/desktop/rake/model/qt.rb:51:in initialize'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in new' C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in class:Executable'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:41:in <top (required)>' C:/Users/FL Studio/Documents/desktop/Rakefile:2:in require_relative'
C:/Users/FL Studio/Documents/desktop/Rakefile:2:in <top (required)>' C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in load'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in load_rakefile' C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in raw_load_rakefile'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in block in load_rakefile' C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in standard_exception_handling'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in load_rakefile' C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in block in run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in standard_exception_handling' C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in <top (required)>' C:/Ruby27-x64/bin/rake:23:in load'
C:/Ruby27-x64/bin/rake:23:in `


anyone nows a clue?

**Comment by ErrorExorY** [comment]
I think I'm doing it wrong. I only open CMD as Admin and then go to the file location and type  "rake"

**Comment by JonathonH-PIA** [comment]
@ErrorExorY Have you installed Qt?  Looks like it was not able to find Qt, but the `nil` conversion got it before the error message was printed.

It basically looks for Qt at `C:\Qt*\5.*\msvc_????_64`.  If your Qt installation is somewhere else, you can set QTROOT, like `rake QTROOT=C:\somewhere\Qt\5.15.0`

You don't need to run CMD as Administrator, but otherwise you should just be able to `rake` in the directory once all the dependencies are installed.

**Comment by ErrorExorY** [comment]
I have QT 5.9.x offline installer installed 
Is that a right version? It sais 5.15 and up

**Comment by ErrorExorY** [comment]
![error](https://user-images.githubusercontent.com/60276799/98828529-78e56480-2438-11eb-93e7-54def0d5199e.png)
This is Now with QTROOT set

**Comment by JonathonH-PIA** [comment]
5.9.9 is too old, try installing 5.15.0.  (You should be able to drop QTROOT, but I guess it would have to be set with slashes, not backslashes; that was primarily tested on Linux IIRC, I'll tweak that too)

**Comment by ErrorExorY** [comment]
I'm at the point to Compile the 5.15 Source but nedd an Commercial license. 
Can I get a compiled version anywhere?
Or is my reading bad? ^^
Is the Online Installer a good Verison for that? What is the QT version of the Online installer?

**Comment by JonathonH-PIA** [comment]
You can get an online installer for the open source version of Qt, go here and scroll all the way to the bottom: https://www.qt.io/download-open-source

Unfortunately Qt no longer provides offline installers for open source, and they make you set up a Qt account now to use the online installer.

5.12 won't work out of the box since we're using the RHI renderer on Windows that isn't present in 5.12.  It might be possible to tweak it to work but it'll be easier to install 5.15.

**Comment by ErrorExorY** [comment]
YES! I see in the online installer. Just like I said. Im a fast reader .. UFF sorry so much.

**Comment by ErrorExorY** [comment]
>rake QTROOT=C:/Qt/5.15.0/mingw81_64
Found Qt: C:/Qt/5.15.0/mingw81_64
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
C:/Users/FL Studio/Documents/desktop/rake/model/qt.rb:60:in `initialize'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in `new'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:43:in `<class:Executable>'
C:/Users/FL Studio/Documents/desktop/rake/executable.rb:41:in `<top (required)>'
C:/Users/FL Studio/Documents/desktop/Rakefile:2:in `require_relative'
C:/Users/FL Studio/Documents/desktop/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by JonathonH-PIA** [comment]
`rake` will figure out the specific Qt build (it'll use the `msvc2019_64` build on 64-bit, that's the native MSVC build as opposed to the MinGW build).

You can likely omit QTROOT and let `rake` find it automatically now that 5.15.0 is installed, or if it doesn't find it, do `rake QTROOT=C:/Qt/5.15.0`

**Comment by ErrorExorY** [comment]
Thank you alot! Now its doing compiling at rake.

**Comment by JonathonH-PIA** [comment]
These build issues are fixed in 2.6.0 👍
