### ISSUE TITLE
I am trying to study your app-based routing that you use for split tunneling, Do you happen to have some kind of flowchart or documentation about it more than contained in the source comments ?

### ISSUE THREAD

**Issue by micronbytes** [pia-foss/desktop#25]
**Describe the solution you'd like**
I would like to know if there is some kind of document outside the repository that could resume the steps, for example in terms of terminal commands executed and code, to achieve Split Tunneling, especially on macOS.

**Describe alternatives you've considered**
I have tried to understand the solution by reading the code, but I still lack a complete understanding of it.

**Additional context**
I am referring to the macOS version of the project. Thanks a lot for your attention.

**Comment by banister** [comment]
Sorry we don't have any additional documentation 😢 But the routing logic is found here; https://github.com/pia-foss/desktop/blob/master/daemon/src/mac/rule_updater.cpp
