### ISSUE TITLE
Blocks LAN filecopy over all FTP, SFTP, SMB, Linux PIA client v1.7

### ISSUE THREAD

**Issue by ampddev** [pia-foss/desktop#3]
Problem only started after upgrading to 1.7

Killswitch enabled
Allow LAN traffic enabled

Trying to copy files > ~50MB from another machine on my LAN always result in a connection time out. But used to work just fine prior to upgrade.

Small files *usually copy
Large files always connection time out
Problem eliminated when exiting PIA client

Linux Mint 19.3
Kernel 5.3.0-24-generic
PIA 1.7 build 03949

**Comment by JonathonH-LTM** [comment]
Hi @ampddev, apologies for the delayed response!

Does this only occur when split tunnel is enabled?  If so, it looks like a routing issue we've found with our split tunnel feature on Linux - packets for LAN hosts are being sent to the default gateway incorrectly.  Many routers seem to forward these anyway, but they don't all do that and we are working on a routing fix.

For now the best workaround is to disable split tunnel.

We're testing a fix by adding a routing rule: `ip rule add pref 99 table main suppress_prefixlength 1` - you can also give this a try by adding this rule manually.

**Comment by JonathonH-PIA** [comment]
Closing, this was likely due to the routing issue for Linux split tunnel that was fixed.
