### ISSUE TITLE
keep publishing up-to-date releases

### ISSUE THREAD

**Issue by piramiday** [pia-foss/desktop#36]
ideally PIA should have some automation scripts built in their process to publish latest versions.

lacking that, PIA developers should still be able to manually publish the latest version **in a timely fashion**.

later version on GH at present is v 2.10.0 which is several months old, as opposed to the new version currently served by the PIA website, v 3.0.1 .

also, there does not seem to be a way to download ARM64 versions of the PIA app from the PIA website.

**Comment by JonathonH-PIA** [comment]
Ouch, sorry about that, thanks for the reminder @piramiday .  You're right that we need proper automation on this, we're doing some work internally on our release process already.

I did publish the 3.0.0 source but forgot to tag the release.  Evidently I forgot to publish 3.0.1 entirely.  Sorry about those lapses, I'm getting those fixed now.

Linux ARM64 and ARMHF builds are available after logging in from the "downloads" tab in the on the left side.  They're still missing from the main downloads page though as you've mentioned, sorry about that too.

**Comment by JonathonH-PIA** [comment]
Those are all up now, thanks again for the reminder!

**Comment by piramiday** [comment]
thanks a lot for your quick replies, Jonathon!

one further thing that might deserve an issue on its own, but which I'll post here as a reply, instead:
can you adjust the release publication process to account for hashsums?
also, why don't you (or someone else in PIA) publish a GPG key and sign the releases (or the hashsums) so that users can trust the releases have not been tampered with?
