### ISSUE TITLE
Add labels to each split-tunneling item

### ISSUE THREAD

**Issue by piramiday** [pia-foss/desktop#37]
it would be useful if one could give **a label** to each split-tunneling item.

if I have set up the IPs of 10 different servers for bypassing PIA, then I will have 10 different IPs in my settings, which makes it quite messy -- just imagine I have to delete an IP... which is which?
labels set up in such a way can also be specified as comments in the `piavpn.r.305.allowSubnets` iptables chain using the `comment` module.

e.g. from:
```
user@host:~$ sudo iptables -L piavpn.r.305.allowSubnets
Chain piavpn.r.305.allowSubnets (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             12.34.56.78
```

to:
```
user@host:~$ sudo iptables -L piavpn.r.305.allowSubnets
Chain piavpn.r.305.allowSubnets (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             12.34.56.78              /* PIA: label */
```

**Comment by banister** [comment]
Thanks for this, it’s a good idea, but it’s not on our road map any time soon, feel free to open a PR though.
