### ISSUE TITLE
qbittorent downloading without vpn

### ISSUE THREAD

**Issue by oklm5fd** [pia-foss/desktop#38]
**Describe the bug**
When I enable Advanced kill switch and disconnect vpn qbittorent still keeps downloading, Internet access for other applications is blocked but not of qbittorent. I have tried toggeling all the options but still it is same. Even when I enable split tunnel and set VPN Only for qbittorent and it will still keep downloading when I turn off VPN.

Issue recreated in attached video.

**Expected behavior**
When I enable Advanced kill switch and split tunnel and set VPN Only for qbittorent and disconnect vpn, qbittorent should stop downloading.

**Observed on:**
 - OS: Windows 10
 - Version 3.2.0

https://user-images.githubusercontent.com/96915916/147827321-ed9edb0a-a949-480d-b44d-020e679e51e4.mp4

**Comment by JonathonH-PIA** [comment]
@oklm5fd, apps often need to be restarted after creating split tunnel rules for them (it's mentioned at the bottom of the Split Tunnel page).  Can you please restart qBittorrent with the rule in place and then verify the advanced kill switch behavior?
