### ISSUE TITLE
pgp signatures or sha checksums of installers

### ISSUE THREAD

**Issue by sifr01** [pia-foss/desktop#41]
It would be better security practice if I could verify if my downloaded VPN client has been subject to a MitM attack. A verifiable publication of sha512 or sha256 checksums would mitigate against that risk. Even better would be a PGP signature of the download or of a checksums file.

Here are the checksums of my download, please can you verify if these are correct?

`$ sha512sum pia-linux-3.3.1-06924.run `
`b4375e95646816d704ea191a758c5bd02299939643d2d81e99e53dcdbecf6167395a339ccbabc8544e78f17ed8d9b845c6f4b9fd34fdff5c6eaeec30fdb56386  pia-linux-3.3.1-06924.run`

`$ sha256sum pia-linux-3.3.1-06924.run `                    
`eee140e511adfac4d74b059ed9d673f1b910163b5b92ac35642a65592fef639d  pia-linux-3.3.1-06924.run`

In the meanwhile, please can people post their checksums of pia-linux-3.3.1-06924.run below so we can begin some form of informal verification. Thanks.

**Comment by JonathonH-PIA** [comment]
SHA-256 checksums are posted here: https://www.privateinternetaccess.com/pages/changelog
Looks like yours matches the checksum for 3.3.1 :+1:

**Comment by sifr01** [comment]
The link you provided doesnt contain checksums for all the releases. For example, its missing android checksums.
