### ISSUE TITLE
Support .deb and Appimage

### ISSUE THREAD

**Issue by dtantono** [pia-foss/desktop#44]
**Is your feature request related to a problem? Please describe.**
.run file is fine. But, for Linux noobs who dislike terminal that will be quite problematic. 

**Describe the solution you'd like**
Support .deb and appimage make installation easier

**Describe alternatives you've considered**

**Additional context**

**Comment by kp-miguel-galindo** [comment]
This is not in our roadmap right now, but we'll consider these.

**Comment by banister** [comment]
This is something we've been discussing - i'll close this issue for now and we'll update the community if we go with something like this! thanks
