### ISSUE TITLE
Network Extension framework on macOS

### ISSUE THREAD

**Issue by Mactastic1-5** [pia-foss/desktop#51]
Shouldn't PIA make use of this new framework by now?

**Comment by MacarioPatrick** [comment]
> Hi @MacarioPatrick ,what specific utility did you have in mind?

Options for it aren't available in Settings on macOS.

**Comment by TheProjectsGuy** [comment]
@banister I think @MacarioPatrick means a setting here
<img width="780" alt="Screenshot 2023-01-26 at 11 42 48 AM" src="https://user-images.githubusercontent.com/29420733/214769854-0cd0d857-9a0a-4868-aebf-1d3c108cf89c.png">

Many other services have a setting here. Is there a way to get this for PIA?

**Comment by Mactastic1-5** [comment]
PIA would make use of System Extensions instead of Network Extensions since the app isn't on the App Store.

**Comment by banister** [comment]
We havent neeed to use apple specific APIs for our app yet, and we generally to avoid it so we can continue to share code between our various platforms. At some point we may look into this though, esp as apple continues to deprecate old APis. Thanks!
