### ISSUE TITLE
[Feature Request] Import custom VPN config files

### ISSUE THREAD

**Issue by zcraber** [pia-foss/desktop#56]
**Is your feature request related to a problem? Please describe.**
No. As of now, the PIA app doesn't support the importing of third-party VPN config files and the app is usable only for PIA users.

**Describe the solution you'd like**
Ability to import any VPN config files and allow the usage of the PIA app without a PIA account.  

**Describe alternatives you've considered**
Windscribe VPN app has this feature. Their app can be used with any VPN provider's config files and doesn't need a Windscribe account.

**Comment by kp-john-mair** [comment]
This is not on our road-map, but feel free to open a PR adding this feature!
