### ISSUE TITLE
Linux app; Qt6/Wayland/KDE?

### ISSUE THREAD

**Issue by RPINerd** [pia-foss/desktop#66]
My PIA is no longer able to used the GUI. Based on a cursory look at the logs, I believe the issue it that Plasma (the KDE desktop environment) has recently updated and now uses both Qt6 and Wayland for the desktop.

Just wanted to have this logged for anyone else having crashes when trying to use the GUI. The actual connection appears to still be active and by using just the toolbar I can manage my connection well enough, but if I accidentally open the GUI I must reboot to get the connection to reestablish..

**Comment by kp-john-mair** [comment]
THanks for the report ! Could you try the following fix? https://privateinternetaccess-storage.s3.amazonaws.com/pub/pia_desktop/builds/pia-linux-3.5.6-wayland.fix.4-08093.run LMK if it works

**Comment by RPINerd** [comment]
> THanks for the report ! Could you try the following fix? https://privateinternetaccess-storage.s3.amazonaws.com/pub/pia_desktop/builds/pia-linux-3.5.6-wayland.fix.4-08093.run LMK if it works

I'm hesitant to run a random file from the internet, can you elaborate a bit on what this file does? Is it patching my existing install or is this a stand alone version of the PIA client just to see if it works?

**Comment by kp-john-mair** [comment]
@RPINerd its a new build for the Linux client that should fix the crashing issue.

**Comment by RPINerd** [comment]
> @RPINerd its a new build for the Linux client that should fix the crashing issue.

GUI appears to work correctly now!
