### ISSUE TITLE
Automations are broken on macOS 14.4

### ISSUE THREAD

**Issue by domco545** [pia-foss/desktop#67]
On macOS 14.4 the "Add Automation Rule" list does not show currently connected network, only the default list options.

Automations such as "Connect" on "Open Wifi" are not working. When I connect to open wifi the VPN stays disconnected even when rule is defined. This is probably related to the issue of not getting the currently connected network.

Last working version of OS was macOS 14.3.1

<img width="704" alt="Screenshot 2024-03-16 at 12 09 33" src="https://github.com/pia-foss/desktop/assets/43946320/69693c02-55cc-442c-be8f-f7a265f644ec">

**Comment by kp-john-mair** [comment]
Hi good catch. Looks like Apple is on an API deprecation rampage! 

please try the following build and lmk if it fixes the issue for you https://privateinternetaccess-storage.s3.amazonaws.com/pub/pia_desktop/builds/pia-macos-3.5.6-08110.zip

**Comment by domco545** [comment]
Hi, the fix works, wifi is back in list and automations are triggering again. There is small issue that first time after install the rules will be picked up only after network change. (Not sure if that was the behaviour before)

https://github.com/pia-foss/desktop/assets/43946320/9689f5d7-78c7-451f-a4fa-24ac7601fa79

**Comment by kp-john-mair** [comment]
Thanks for the feedback. This isn't a regression, it only triggers on network change events. We can look into tweaking this behavior in the future future though.

We will push a new release soon with the fix you tested. Thanks again!
