### ISSUE TITLE
Very small UI

### ISSUE THREAD

**Issue by sang-shelton** [pia-foss/desktop#71]
This is how the PIA Linux app UI looks like compared to the rest of the DE

![Screenshot_20240731_030321](https://github.com/user-attachments/assets/41d05439-8a20-4bd2-8938-8482be34e873)

![Screenshot_20240731_030553](https://github.com/user-attachments/assets/bff0ec12-c643-4b3f-83a7-64858cda7626)

I am using Manjaro Linux with KDE and my "Global scale" is 175%

![Screenshot_20240731_030723](https://github.com/user-attachments/assets/7f3b7617-3ebd-4405-ad47-726aa7f2be3a)

I think this problem is happening cuz the PIA app is using an older version of Qt, similar issue happens when using apps written in GTK2. GTK3 apps scale well.

<details><summary>System info</summary>
<p>

```
Operating System: Manjaro Linux 
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.10-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 32 × AMD Ryzen 9 5950X 16-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C91
System Version: 1.0
```

</p>
</details>

**Comment by skyronic** [comment]
I'm not sure - but I think PIA uses the `QT_SCALE_FACTOR` on KDE environments as specified [here](https://github.com/pia-foss/desktop/blob/522751571ea7f6b1a9e3dd5cc4c70fc2fd136221/client/src/linux/linux_scaler.cpp#L275-L279). You can check if that env value is set.

It also looks like it reads the GSettings value `org.gnome.desktop.interface.scaling-factor` - so you can verify if that value has been set.

I believe you can also override all these values using the env var `PIA_SCALE`. You'll have to set it before starting the client!

**Comment by kp-miguel-galindo** [comment]
Hey @sang-shelton. We released a beta for pia desktop that uses Qt6. Your setup using a scale of 175 is unusualish, but perhaps you could try how it looks in the beta?

**Comment by sang-shelton** [comment]
> Hey @sang-shelton. We released a beta for pia desktop that uses Qt6. Your setup using a scale of 175 is unusualish, but perhaps you could try how it looks in the beta?

where can i find that beta release ?

**Comment by sang-shelton** [comment]
> I believe you can also override all these values using the env var `PIA_SCALE`. You'll have to set it before starting the client!

`PIA_SCALE=2` worked fine with me, now the UI displays correctly, thanks.

**Comment by sang-shelton** [comment]
> @sang-shelton you can get the beta by going to Settings -> Help -> Receive Beta updates

The beta release works fine and the UI displays correctly by default without the need to add `PIA_SCALE=2`.

However the UI has some weird stuff, but it aint a big deal.

![Screenshot_20240731_101520](https://github.com/user-attachments/assets/df3f6abf-cdde-4969-99dc-46cc5c5294a9)

![Screenshot_20240731_101606](https://github.com/user-attachments/assets/89f14098-f599-477e-aee2-b15ff058fa1f)
